### ISSUE TITLE
[Chord] Defenir le lancement de l'application

### ISSUE THREAD

**Issue by PhilyT** [PhilyT/SystemDistrib#16]
Par défaut il initialise juste le ChordPeer avec une adress ip, une clé et un port de base.
Sinon il initialise le chordPeer avec un adresse ip, une clé et un port donné par l'utilisateur et join le chord par défaut.

**Comment by marouaneml** [comment]
les commande disponibles 
Options:
	-I: afficher les infos du ChordPeer courant
	-C: chatter avec un chordPeer
	-Q: quitter
rq: la commande cls pour effacer l'ecran est disponible aussi ;)
résultat: lancez l'app et tester chaque commande
